import { WORKSPACE_CONTRACT_VERSION } from "@codexhost/shared-contracts";

export { validateHostApprovalResponse } from "./approval.js";
export { validateHostInteractionResponse } from "./interaction.js";
export { HarnessOutputChannel } from "./output-channel.js";
export { sanitizeDiagnosticTail } from "./diagnostics.js";
export { validateHostQuestionResponse } from "./question.js";
export { parseHostUsage } from "./usage.js";
export { validateHostFileInputs } from "./file-input-validation.js";
export type {
  HostFileInputProbe,
  HostFileInputValidationOptions,
} from "./file-input-validation.js";
export {
  HOST_FILE_INPUT_MARKER,
  hostFileInputLine,
  hostInputFiles,
  hostInputPromptText,
  hostInputText,
} from "./turn-input.js";
export type { HostUsage } from "./usage.js";
export type {
  AutonomousTurnStartedEvent,
  CreateSessionInput,
  ForkSessionInput,
  HarnessAdapter,
  HarnessCommandAccepted,
  HarnessCommandCapability,
  HarnessCommandInvocation,
  HarnessError,
  HarnessErrorCode,
  HarnessExecutionPolicy,
  HarnessInspection,
  HarnessModel,
  HarnessModelCatalog,
  HarnessModelRef,
  HarnessPermissionMode,
  HarnessPermissionModeCatalog,
  HarnessPermissionModeId,
  HarnessOutput,
  HarnessResult,
  HarnessSession,
  HarnessSessionCapabilities,
  HarnessSessionImportCandidate,
  HarnessSessionImportCapability,
  HarnessSessionImportSource,
  HarnessSubagentCapability,
  HarnessWebUiAction,
  HarnessSessionState,
  HarnessThinkingOption,
  HarnessThinkingOptionId,
  HostAgentMessageItem,
  HostUserMessageItem,
  HostApprovalAction,
  HostApprovalEffect,
  HostApprovalInteraction,
  HostApprovalResponse,
  HostChoiceQuestion,
  HostCommand,
  HostCommandExecutionItem,
  HostContextCompactionItem,
  HostEvent,
  HostFileChange,
  HostFileChangeItem,
  HistoricalTurnOutcome,
  HostInteraction,
  HostInteractionResponse,
  HostItem,
  HostItemOutcome,
  HostItemSnapshot,
  HostItemUpdate,
  HostQuestion,
  HostQuestionInteraction,
  HostQuestionResponse,
  HostReasoningItem,
  HostSubagentDelegationItem,
  HostSubagentState,
  HostSubagentStatus,
  HostThreadSnapshot,
  HostFileInput,
  HostInput,
  HostTextInput,
  HostTextQuestion,
  HostToolExecutionItem,
  HostToolOutput,
  HostTurnSnapshot,
  InteractionClosedEvent,
  InteractionRespondAccepted,
  InteractionRespondCommand,
  ItemCompletedEvent,
  ItemStartedEvent,
  InspectHarnessInput,
  ItemUpdatedEvent,
  ModelSelectCommand,
  ModelSelectCompleted,
  OpenSessionInput,
  PermissionModeSelectCommand,
  PermissionModeSelectCompleted,
  ResumeSessionInput,
  RollbackLastTurnSessionInput,
  SessionFaultedEvent,
  SessionStateChangedEvent,
  SessionUsageChangedEvent,
  SubagentStateChangedEvent,
  SubagentTranscriptChangedEvent,
  ThinkingSelectCommand,
  ThinkingSelectCompleted,
  TurnCompletedEvent,
  TurnCancelAccepted,
  TurnCancelCommand,
  TurnOutcome,
  TurnStartAccepted,
  TurnStartCommand,
  TurnSteerAccepted,
  TurnSteerCommand,
  TurnStartedEvent,
} from "./text-session.js";

export const packageMetadata = {
  name: "@codexhost/harness-adapter",
  contractVersion: WORKSPACE_CONTRACT_VERSION,
} as const;
